version: '3'
name: nara_sample_test
services:
  webapi:
    image: naraspace/sample_webapi:0.1
    container_name: webapi
    build:
      context: ./flask
    ports:
      - "5900:5900"
    volumes:
      - ./flask/src:/app
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #     - db
  # redis:
  #   image: "redis:latest"
  # db:
  #   image: "postgres:13"
  #   environment:
  #     POSTGRES_DB: yourdb
  #     POSTGRES_USER: youruser
  #     POSTGRES_PASSWORD: yourpassword