version: '3'
name: nara_sample_test
services:
  webapi:
    image: naraspace/fastapi_webapi:0.1
    container_name: webapi
    build:
      context: ./fastapi
    ports:
      - "5900:5900"
    volumes:
      - ./fastapi/src:/app
  